---
title: "Untitled"
format: html
---

```{r}
r <- 8; p <- 5
simulate_group <- function(n, mean_matrix, row_sd = 0.5, col_sd = 0.5) {
	row_cov <- diag(row_sd, nrow(mean_matrix))
	col_cov <- diag(col_sd, ncol(mean_matrix))
	lapply(seq_len(n), function(i) mean_matrix + row_cov %*% matrix(rnorm(r * p), r, p) %*% col_cov)
}

M1 <- matrix(1, r, p)
M2 <- matrix(-1, r, p)
x_list <- c(simulate_group(80, M1), simulate_group(40, M2))

contam <- lapply(seq_len(15), function(i) matrix(runif(r*p, -1, 1), r, p))
x_list <- c(x_list, contam)
```


```{r}
library(RIMLEMV)
library(mclust)
set.seed(NULL)

rimle_fit(x_list, g = 2, estimate_k = TRUE, init = "hennig-coretto", verbose = TRUE, nstart = 1, q = 4)

rimle_fit(x_list_viroli, g = 3, estimate_k = TRUE, init = "hennig-coretto", verbose = TRUE, nstart = 1, q = 4)
```


```{r}
library(clusterGeneration)

r_viroli <- 3; p_viroli <- 5
n_viroli <- 300

# Viroli-style mean matrices (3x5 with first column containing a,b values)
M1_viroli <- matrix(c(0.5, 0.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), nrow = r_viroli, ncol = p_viroli, byrow = FALSE)
M2_viroli <- matrix(0, r_viroli, p_viroli)
M3_viroli <- matrix(c(-0.5, 0.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), nrow = r_viroli, ncol = p_viroli, byrow = FALSE)

# Generate random U and V matrices
U1_viroli <- rcorrmatrix(r_viroli)
V1_viroli <- rcorrmatrix(p_viroli)
U2_viroli <- rcorrmatrix(r_viroli)
V2_viroli <- rcorrmatrix(p_viroli)
U3_viroli <- rcorrmatrix(r_viroli)
V3_viroli <- rcorrmatrix(p_viroli)

# Simulate groups with Viroli proportions (0.3, 0.4, 0.3)
n1_viroli <- round(0.3 * n_viroli)
n2_viroli <- round(0.4 * n_viroli)
n3_viroli <- n_viroli - n1_viroli - n2_viroli

simulate_matrix_group <- function(n, mean_mat, row_cov, col_cov) {
  lapply(seq_len(n), function(i) {
    mean_mat + row_cov %*% matrix(rnorm(r_viroli * p_viroli), r_viroli, p_viroli) %*% col_cov
  })
}

x_list_viroli <- c(
  simulate_matrix_group(n1_viroli, M1_viroli, U1_viroli, V1_viroli),
  simulate_matrix_group(n2_viroli, M2_viroli, U2_viroli, V2_viroli),
  simulate_matrix_group(n3_viroli, M3_viroli, U3_viroli, V3_viroli)
)

# Add permuted outliers (15 matrices with permuted entries)
outlier_idx_viroli <- sample(length(x_list_viroli), 15)
for (idx in outlier_idx_viroli) {
  x_list_viroli[[idx]] <- matrix(sample(x_list_viroli[[idx]]), r_viroli, p_viroli)
}
```

